### ISSUE TITLE
Error: Source path does not exist: resources/ios/icon/icon-40@3x.png

### ISSUE THREAD

**Issue by malkitsingh** [ionic-team/ionic-default-resources#1]
Hi, I have Ionic Version 1.7.16 installed
and Cordova 6.3.0 installed.

Whenever I try to add iOS platform using ionic platform add ios , I get this error
Error: Source path does not exist: resources/ios/icon/icon-40@3x.png

I think this file is missing from repo here.
Or is there any other way to fix this issue?

**Comment by hashans** [comment]
I'm also facing the same issue.

**Comment by yas-bo-dev** [comment]
Hi, 
I have also the same issue.
Any fix ?

**Comment by dagmawim** [comment]
Check and see if you specified a file in your config.xml that does not exist or is not where you thought it was, this was my issue

**Comment by ericdesj** [comment]
Try using `$ ionic resources` and run `$ ionic emulate ios`

**Comment by githubramakrishnan** [comment]
hi @malkitsingh ,

I also got the error you mentioned.
i have tried with **ionic resources --icon** command and its working fine now.

**Comment by MatheusSilva96** [comment]
please can someone use `ionic resources --icon` and update this ionic default resources?

**Comment by mlynch** [comment]
Fixed in e22f838aef6e6eeb7fadd759fbb55ca4fedf2a0c

**Comment by malkitsingh** [comment]
finally max (Y)

**Comment by mateo6454** [comment]
Error: Source path "C:/HaxeToolkit/haxe/lib/systools/1,1,0/ndll/Windows64/systools.ndll" does not exist
